// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sdfhagnfjqfenftfjtif.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNkZmhhZ25manFmZW5mdGZqdGlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMTMxMjYsImV4cCI6MjA2MzU4OTEyNn0.JXOPh4DduEMb5lGlI7ESwH7r-1O1KSMs5-2WshMtoxo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);